/* all_dtypes.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 1
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 8
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"t_f16", "f16", "cpu0", {4,4}, 2},
    {"t_f32", "f32", "cpu0", {4,4}, 2},
    {"t_bf16", "bf16", "cpu0", {4,4}, 2},
    {"t_i8", "i8", "cpu0", {4,4}, 2},
    {"t_i16", "i16", "cpu0", {4,4}, 2},
    {"t_i32", "i32", "cpu0", {4,4}, 2},
    {"t_i64", "i64", "cpu0", {4,4}, 2},
    {"t_u8", "u8", "cpu0", {4,4}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 1
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k0", "aten.cast", "t_f32", "t_f16"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 1
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g0", {"k0"}, 1}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 1
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"iso0", "inner", "g0", {}, 0}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 0
