/* dtecho_multi_isolate.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 2
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=4"},
    {"gpu0", "kind=cuda,sm=80"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 5
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"intent_in", "f32", "cpu0", {1,512}, 2},
    {"evidence_out", "f32", "cpu0", {1,512}, 2},
    {"branch_h", "f32", "gpu0", {1,1024}, 2},
    {"leaf_h", "f32", "gpu0", {1,256}, 2},
    {"prov", "f32", "cpu0", {1,4}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 5
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k_enc", "dtecho.encode", "intent_in,prov", "branch_h"},
    {"k_branch", "dtecho.branch", "branch_h", "leaf_h"},
    {"k_leaf", "dtecho.leaf", "leaf_h", "leaf_h"},
    {"k_up", "dtecho.echo", "leaf_h,prov", "branch_h"},
    {"k_dec", "dtecho.decode", "branch_h", "evidence_out"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 3
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g_leaf", {"k_leaf"}, 1},
    {"g_branch", {"k_branch","k_up"}, 2},
    {"g_root", {"k_enc","k_dec"}, 2}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 3
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"leaf_iso", "inner", "g_leaf", {{"task","Intent"},{"result","Evidence"},{"state","Tensor"}}, 3},
    {"branch_iso", "trans", "g_branch", {{"up_in","Intent"},{"up_out","Evidence"},{"dn_out","Intent"},{"dn_in","Evidence"},{"control","Bytes"}}, 5},
    {"root_iso", "outer", "g_root", {{"intent","Intent"},{"evidence","Evidence"},{"status","Tensor"},{"ctrl","Bytes"}}, 4}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 3
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"leaf_pol", {{"inner","denies","toolcall",NULL},{"inner","denies","external_io",NULL}}, 2},
    {"branch_pol", {{"trans","allows","evidence","provenance>=0.7"},{"trans","allows","intent","depth<=10"}}, 2},
    {"root_pol", {{"outer","allows","intent","budget.tokens<=8192"},{"outer","allows","evidence","echo.complete==1"}}, 2}
};
