/* dtecho_depth_first.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 2
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=8"},
    {"gpu0", "kind=cuda,sm=80"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 6
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"input_vec", "f32", "cpu0", {1,1024}, 2},
    {"output_vec", "f32", "cpu0", {1,1024}, 2},
    {"root_state", "f32", "gpu0", {1,1024}, 2},
    {"branch_l1", "f32", "gpu0", {1,512}, 2},
    {"branch_l2", "f32", "gpu0", {1,256}, 2},
    {"leaf_state", "f32", "gpu0", {1,128}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 5
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k_root_down", "dtecho.root_down", "input_vec,root_state", "branch_l1"},
    {"k_root_up", "dtecho.root_up", "branch_l2,root_state", "output_vec"},
    {"k_branch_down", "dtecho.branch_down", "branch_l1", "branch_l2"},
    {"k_branch_up", "dtecho.branch_up", "leaf_state", "branch_l2"},
    {"k_leaf", "dtecho.leaf_compute", "branch_l2", "leaf_state"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 3
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g_leaf", {"k_leaf"}, 1},
    {"g_branch", {"k_branch_down","k_branch_up"}, 2},
    {"g_root", {"k_root_down","k_root_up"}, 2}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 3
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"leaf_dfs", "inner", "g_leaf", {{"task","Intent"},{"result","Evidence"},{"state","Tensor"}}, 3},
    {"branch_dfs", "trans", "g_branch", {{"parent_in","Intent"},{"parent_out","Evidence"},{"child_out","Intent"},{"child_in","Evidence"}}, 4},
    {"root_dfs", "outer", "g_root", {{"intent","Intent"},{"evidence","Evidence"},{"control","Bytes"}}, 3}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 1
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"dfs_policy", {{"inner","denies","toolcall",NULL},{"inner","denies","external_io",NULL},{"trans","allows","intent","depth<=16"},{"trans","allows","evidence","provenance>=0.5"},{"outer","allows","intent",NULL},{"outer","allows","evidence",NULL}}, 6}
};
