/* dtecho_basic.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 2
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=8"},
    {"gpu0", "kind=cuda,sm=86"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 5
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"intent_vec", "f32", "cpu0", {1,512}, 2},
    {"branch_state", "f32", "gpu0", {1,1024}, 2},
    {"leaf_state", "f32", "gpu0", {1,256}, 2},
    {"evidence_vec", "f32", "cpu0", {1,512}, 2},
    {"provenance", "f32", "cpu0", {1,4}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 5
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k_encode", "dtecho.encode", "intent_vec,provenance", "branch_state"},
    {"k_branch", "dtecho.branch", "branch_state", "leaf_state"},
    {"k_compute", "dtecho.leaf", "leaf_state", "leaf_state"},
    {"k_echo", "dtecho.echo", "leaf_state,provenance", "branch_state"},
    {"k_decode", "dtecho.decode", "branch_state", "evidence_vec"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 3
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g_leaf", {"k_compute"}, 1},
    {"g_branch", {"k_branch","k_echo"}, 2},
    {"g_coordinator", {"k_encode","k_decode"}, 2}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 3
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"leaf_node", "inner", "g_leaf", {{"task_in","Intent"},{"result_out","Evidence"},{"state","Tensor"}}, 3},
    {"branch_node", "trans", "g_branch", {{"parent_in","Intent"},{"parent_out","Evidence"},{"child_out","Intent"},{"child_in","Evidence"},{"control","Bytes"}}, 5},
    {"echo_coordinator", "outer", "g_coordinator", {{"intent","Intent"},{"evidence","Evidence"},{"status","Tensor"},{"control","Bytes"}}, 4}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 1
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"echo_policy", {{"inner","denies","toolcall",NULL},{"inner","denies","external_io",NULL},{"trans","allows","evidence","provenance>=0.7"},{"trans","allows","intent","depth<=8"},{"outer","allows","intent","budget.tokens<=4096"},{"outer","allows","evidence","echo.complete==1"}}, 6}
};
