/* dtecho_provenance.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 2
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=4"},
    {"gpu0", "kind=cuda,sm=80"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 4
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"provenance", "f32", "cpu0", {1,4}, 2},
    {"intent_vec", "f32", "cpu0", {1,512}, 2},
    {"evidence_vec", "f32", "cpu0", {1,512}, 2},
    {"branch_state", "f32", "gpu0", {1,1024}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 5
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k_init_prov", "dtecho.init_provenance", "intent_vec", "provenance"},
    {"k_encode", "dtecho.encode", "intent_vec,provenance", "branch_state"},
    {"k_process", "dtecho.process", "branch_state,provenance", "branch_state"},
    {"k_decay_prov", "dtecho.decay_provenance", "provenance", "provenance"},
    {"k_decode", "dtecho.decode", "branch_state,provenance", "evidence_vec"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 1
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g_prov_echo", {"k_init_prov","k_encode","k_process","k_decay_prov","k_decode"}, 5}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 1
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"prov_echo", "trans", "g_prov_echo", {{"intent_in","Intent"},{"evidence_out","Evidence"},{"prov_stat","Tensor"},{"control","Bytes"}}, 4}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 1
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"prov_policy", {{"inner","denies","toolcall",NULL},{"inner","denies","external_io",NULL},{"trans","allows","evidence","(provenance>=0.6 and depth<=12)"},{"trans","denies","evidence","provenance<0.6"},{"outer","allows","intent","budget.tokens<=8192"},{"outer","allows","evidence","echo.complete==1"}}, 6}
};
