/* empty_program.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 0

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 0

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 0

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 0

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 0

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 0
