/* multi_device.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 3
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=8"},
    {"gpu0", "kind=cuda,sm=80"},
    {"gpu1", "kind=cuda,sm=86"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 5
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"x", "f16", "cpu0", {1,128,4096}, 3},
    {"w0", "f16", "gpu0", {4096,4096}, 2},
    {"w1", "f16", "gpu1", {4096,4096}, 2},
    {"y0", "f16", "gpu0", {1,128,4096}, 3},
    {"y1", "f16", "gpu1", {1,128,4096}, 3}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 2
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k0", "aten.matmul", "x,w0", "y0"},
    {"k1", "aten.matmul", "x,w1", "y1"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 1
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g_parallel", {"k0","k1"}, 2}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 1
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"parallel_compute", "inner", "g_parallel", {{"inp","Tensor"},{"out0","Evidence"},{"out1","Evidence"}}, 3}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 1
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"mem", {{"inner","denies","toolcall",NULL},{"outer","allows","intent",NULL}}, 2}
};
