/* policy_complex.h - generated by vnpu compiler */
/* DO NOT EDIT */
#pragma once
#include <stdint.h>

/* ---- Type Definitions ---- */
typedef struct { const char *name; const char *props; } VnpuDevice;

typedef struct {
    const char *name, *dtype, *device;
    int dims[8]; int ndims;
} VnpuTensor;

typedef struct {
    const char *name, *qualop, *args, *output;
} VnpuKernel;

typedef struct {
    const char *name;
    const char *stmts[32]; int nstmts;
} VnpuGraph;

typedef struct { const char *name, *porttype; } VnpuPort;

typedef struct {
    const char *name, *membrane, *entry;
    VnpuPort ports[8]; int nports;
} VnpuIsolate;

typedef struct {
    const char *membrane, *action, *subject, *condition;
} VnpuPolicyRule;

typedef struct {
    const char *name;
    VnpuPolicyRule rules[8]; int nrules;
} VnpuPolicy;

/* --- Device Declarations --- */
#define VNPU_NUM_DEVICES 1
static VnpuDevice vnpu_devices[VNPU_NUM_DEVICES] = {
    {"cpu0", "kind=cpu,threads=4"}
};

/* --- Tensor Declarations --- */
#define VNPU_NUM_TENSORS 2
static VnpuTensor vnpu_tensors[VNPU_NUM_TENSORS] = {
    {"a", "f32", "cpu0", {16,16}, 2},
    {"b", "f32", "cpu0", {16,16}, 2}
};

/* --- Kernel Declarations --- */
#define VNPU_NUM_KERNELS 2
static VnpuKernel vnpu_kernels[VNPU_NUM_KERNELS] = {
    {"k0", "aten.add", "a,b", "a"},
    {"k1", "aten.mul", "a,b", "b"}
};

/* --- Graph Declarations --- */
#define VNPU_NUM_GRAPHS 1
static VnpuGraph vnpu_graphs[VNPU_NUM_GRAPHS] = {
    {"g0", {"k0","k1"}, 2}
};

/* --- Isolate Declarations --- */
#define VNPU_NUM_ISOLATES 1
static VnpuIsolate vnpu_isolates[VNPU_NUM_ISOLATES] = {
    {"iso0", "inner", "g0", {{"inp","Intent"},{"outp","Evidence"},{"ctrl","Bytes"}}, 3}
};

/* --- Policy Declarations --- */
#define VNPU_NUM_POLICIES 1
static VnpuPolicy vnpu_policies[VNPU_NUM_POLICIES] = {
    {"pcomplex", {{"inner","denies","toolcall",NULL},{"inner","denies","external_io",NULL},{"trans","allows","evidence","(provenance>=0.8 and budget.tokens<=2048)"},{"trans","denies","intent","depth>16"},{"trans","allows","intent","budget.requests<=100"},{"outer","allows","intent","budget.tokens<=8192"},{"outer","allows","evidence","echo.complete==1"}}, 7}
};
